### ISSUE TITLE
ClassCastException on anonymous classes subscriptions

### ISSUE THREAD

**Issue by sdhaliwal** [intendia-oss/autorest#8] opened 2018-05-03 18:51 UTC
Hi,
 This is not really an issue but I was wondering if there was a plan to release version 1.0 in near future. We have been using this awesome library and it has been working really well. 

Only one inconvenience is that on the Client while subscribing to the Observable a lambda must be used, otherwise a ClassCastException is thrown.

**Comment by ibaca** [comment] 2018-05-04 11:43
Can you add a code example that causes the ClassCastException? Thanks! 😄

**Comment by sdhaliwal** [comment] 2018-05-04 13:34
**Please see the code below 
//the method call the produces the error. Service and dto definitions follow**

`    private void testGetAppInitInfo() {
        service.getAppInitInfo().subscribe(new Action1<UhmAppInfo>() {
            @Override
            public void call(UhmAppInfo uhmAppInfo) {
                ClientLoggingUtil.info(uhmAppInfo.key);
            }
        });
    }

**//Service definition**
@Path("uhmService")
@Consumes("application/json")
@Produces("application/json")
@AutoRestGwt
public interface UhmService {
    @GET
    @Path("/getAppInitInfo")
    Single<UhmAppInfo> getAppInitInfo();
}

// dto definition
@JsType
public class UhmAppInfo extends BasePureDTO {
    public String nickName = "";
    public String siteId = "";
    public String locationUid = "";
    public String locationName = "";
    public String[] permissions = {};

}

@JsType(namespace = JsPackage.GLOBAL, name = "BasePureDTO")
public class BasePureDTO {
    public String key = "";
}
`
Please let me know if additional information is required.
BTW, we think that your ideas of using the PureDTOs and keeping the framework minimalistic are wonderful and have been working very nicely for us. We are using these to develop a very large application.

**Comment by ibaca** [comment] 2018-05-06 19:02
🙌 nice, yep we use it internally in a reasonably big application and it is kind of a surprise how with a few limitations this minimal lib solves the whole problem. So it awesome that the idea that this lib tries to share has been applied in other projects. I'm not too worried in releases bc one pretty good thing about this lib is that is more a "blueprint" or a "pattern" on how to organize and apply limits to your transport layer to make it trivial to implement it. So eventually you can always copy this few lines of codes and continue it in your own project.

I have tried to reproduce the error but it doesn't fail 😞. Maybe a whole project on github? something like https://github.com/ibaca/java10-gwt

Strongly recommended migrating to rxjava2 😉we are using it in production already!

**Comment by sdhaliwal** [comment] 2018-05-08 12:58
Thanks for the detailed reply and your time. The default implementation has been working nicely for us. I will try to create  a simple app and post it on github to demonstrate the ClassCastException. May be we are not using something correctly. Like I said it is a minor inconvenience. We should be using Lambdas anyways. So not a big issue

**Comment by ibaca** [comment] 2018-05-08 14:04
Yep, but looks likes some weird edge case, now I'm curious. Most probably this is a GWT (actually eclipse ECJ) compiler problem, and it might already be fixed in GWT HEAD-SNAPSHOT. On the other side, DTOs has some unexpected behaviors that can throw some class cast exceptions too. We will see 👍.

**Comment by sdhaliwal** [comment] 2018-05-15 12:32
Migrated to rxjava2 without an issue. Thanks for the recommendation. autorest-gwt works well without any modification. still trying to create a small project showing the ClassCast exception.

**Comment by ibaca** [comment] 2018-05-18 06:47
I released autorest 0.8 with a minor change to make it work with rxjava 2 out of the box. But looks like you have your own RequestResourceBuilder implementation, aren't you? 

FYI this gitter chat is a good place to ask questions or sharing gwt experiences!
https://gitter.im/gwtproject/gwt

I'm going to rename this issue as "ClassCastException on anonymous classes".

**Comment by sdhaliwal** [comment] 2018-05-18 13:17
Awesome, thanks for the new release. We are actually using the RequestResourceBuilder generated by the autorest-processor. As I mentioned earlier this has been working great except for the ClassCastException. I apologize the things have been hectic here with the project but I still owe you an application to demonstrate the exception. I am going to include my generated code here to see if something seems odd about it.
`
import static javax.ws.rs.HttpMethod.GET;
import static javax.ws.rs.HttpMethod.POST;

import com.intendia.gwt.autorest.client.ResourceVisitor;
import com.intendia.gwt.autorest.client.RestServiceModel;
import java.lang.Override;
import java.lang.String;
import java.lang.Void;
import javax.inject.Inject;
import mil.housing.uhm.shared.dtos.LabelValueDTO;
import mil.housing.uhm.shared.dtos.UhmAppInfo;
import mil.housing.uhm.shared.dtos.UhmContextDTO;
import mil.housing.uhm.shared.dtos.sample.SampleDTO;
import rx.Completable;
import rx.Observable;
import rx.Single;

public class UhmService_RestServiceModel extends RestServiceModel implements UhmService {
  @Inject
  public UhmService_RestServiceModel(final ResourceVisitor.Supplier parent) {
    super(new ResourceVisitor.Supplier() { public ResourceVisitor get() { return parent.get().path("uhmService"); } });
  }


  @Override
  public Single<UhmAppInfo> getAppInitInfo() {
    return method(GET).path("getAppInitInfo").produces("application/json").consumes("application/json").as(Single.class, UhmAppInfo.class);
  }
}

import com.google.gwt.core.client.GWT;
import com.intendia.gwt.autorest.client.RequestResourceBuilder;
import com.intendia.gwt.autorest.client.ResourceVisitor;

public class AutoRestUtil {
    public static ResourceVisitor osm() {
        return new RequestResourceBuilder().path(GWT.getHostPageBaseURL() + "rest");
    }
}

UhmService service = new UhmService_RestServiceModel(AutoRestUtil::osm);
`

Thanks for Sharing the Gitter url. I will start using that.

**Comment by ibaca** [comment] 2018-06-10 21:19
I'm going to close this bc it is pretty improbable that the class-cast problem to be an AutoREST bug. We can continue the class-cast discussion here or in gitter 👍.

**Closed by ibaca** 2018-06-10 21:19 UTC
